import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
    await page.getByLabel('Menu', { exact: true }).click();
    await page.getByRole('link', { name: 'Configuration', exact: true }).click();
    await page.getByRole('link', { name: 'Configuration' }).click();
    await page.getByRole('link', { name: 'Request Configuration' }).click();
    await expect(page.getByRole('heading', { name: 'Request Configuration' })).toBeVisible();
    await expect(page.locator('form')).toContainText('Request Configuration');
    await expect(page.getByLabel('Add Request')).toBeVisible();
    await expect(page.getByLabel('Add Request')).toBeVisible();
    await expect(page.locator('mat-tooltip-component')).toContainText('Add Request');
    await page.getByLabel('Add Request').click();
    await expect(page.locator('h2')).toContainText('Request Configuration');
    await page.getByLabel('title').click();
    await page.getByLabel('title').fill('qaMultAppr');
    await page.locator('#custom-mat-multiselect-id-4').getByRole('button').click();
    await page.getByText('Pre arrival', { exact: true }).click();
    await page.getByRole('listbox').press('Tab');
    await page.getByText('check_box', { exact: true }).click();
    await page.locator('div').filter({ hasText: /^check_box_outline_blank Pre arrival$/ }).locator('mat-icon').click();
    await page.locator('.cdk-overlay-backdrop').click();
    await page.locator('#custom-mat-multiselect-id-5').getByRole('button').click();
    await page.getByLabel('Search').click();
    await page.getByLabel('Search').fill('f-1');
    await page.getByText('F-').click();
    await page.locator('#cdk-overlay-34').getByRole('button').click();
    await page.getByLabel('Search').click();
    await page.getByLabel('Search').fill('f');
    await page.getByText('check_box F-').click();
    await page.getByText('check_box_outline_blank F-').click();
    await page.locator('.cdk-overlay-backdrop').click();
    await page.getByRole('button', { name: 'Next' }).click();
    await expect(page.locator('mat-card-title')).toContainText('Active Components');
    await page.getByLabel('Add Component').click();
    await page.getByRole('menuitem', { name: 'Assessment' }).click();
    await page.getByRole('textbox', { name: 'title' }).click();
    await page.getByRole('textbox', { name: 'title' }).fill('test A');
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.locator('.cdk-overlay-container > div:nth-child(3)').click();
    await page.getByLabel('Scoring Mechanism *').locator('span').click();
    await page.getByText('Highest Score').click();
    await page.getByLabel('Assessment Attempts *').click();
    await page.getByRole('button', { name: 'Cancel' }).click();
    await page.getByLabel('Add Component').click();
    await page.getByRole('menuitem', { name: 'Approver Form' }).click();
    await page.getByRole('textbox', { name: 'title' }).click();
    await page.getByRole('textbox', { name: 'title' }).fill('approver uno');
    await page.getByLabel('Add component', { exact: true }).click();
    await page.getByRole('menuitem', { name: 'Student Submission', exact: true }).click();
    await page.getByRole('button', { name: 'Student submission' }).click();
    await page.getByLabel('Add component', { exact: true }).click();
    await page.getByRole('menuitem', { name: 'Information Block' }).click();
    await page.getByRole('button', { name: 'Information' }).click();
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.getByLabel('Add Component').click();
    await page.getByRole('menuitem', { name: 'Approver Form' }).click();
    await page.getByRole('textbox', { name: 'title' }).click();
    await page.getByRole('textbox', { name: 'title' }).fill('approver dos');
    await page.getByLabel('Add component', { exact: true }).click();
    await page.getByRole('menuitem', { name: 'Questionnaire' }).click();
    await page.getByRole('button', { name: 'Questionnaire' }).click();
    await page.getByRole('button', { name: 'Questionnaire' }).click();
    await page.getByRole('button', { name: 'Questionnaire' }).click();
    await page.locator('div').filter({ hasText: /^ISSS-3903 logadd$/ }).nth(1).click();
    await page.getByLabel('Approver Formclose').click();
    await page.getByRole('button', { name: 'Questionnaire' }).click();
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.getByRole('button', { name: 'Save' }).click();
    await page.getByLabel('Search Configuration').click();
    await page.getByRole('combobox', { name: 'Search Configuration' }).fill('qa');
    await page.getByRole('combobox', { name: 'Search Configuration' }).press('Enter');
    await page.getByRole('combobox', { name: 'Search Configuration' }).fill('qaMultiAppr');
    await page.getByRole('combobox', { name: 'Search Configuration' }).press('Enter');
    await page.getByRole('combobox', { name: 'Search Configuration' }).fill('qaMult');
    await page.getByRole('combobox', { name: 'Search Configuration' }).press('Enter');
    await expect(page.getByRole('table')).toContainText('qaMultAppr');
});